services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev
    environment:
      NODE_ENV: development
      PORT: ${PORT:-5200}
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    volumes:
      - ./:/app
      - api_node_modules:/app/node_modules

volumes:
  api_node_modules:
