variable "aws_region" {
  description = "AWS region used by every resource."
  type        = string
  default     = "eu-central-1"
}

variable "project_name" {
  description = "Lowercase project identifier used in resource names."
  type        = string
  default     = "zwanga-api"

  validation {
    condition     = can(regex("^[a-z0-9-]+$", var.project_name))
    error_message = "project_name must contain only lowercase letters, digits and hyphens."
  }
}

variable "environment" {
  description = "Deployment environment, for example production or staging."
  type        = string
  default     = "production"

  validation {
    condition     = can(regex("^[a-z0-9-]+$", var.environment))
    error_message = "environment must contain only lowercase letters, digits and hyphens."
  }
}

variable "github_owner" {
  description = "GitHub organization or username allowed to assume the deployment role."
  type        = string
}

variable "github_repository" {
  description = "GitHub backend repository allowed to deploy."
  type        = string
  default     = "zwanga-api"
}

variable "github_branch" {
  description = "Only this Git branch can assume the deployment role."
  type        = string
  default     = "release"
}

variable "github_actions_role_name" {
  description = "Name of the IAM role assumed by GitHub Actions through OIDC."
  type        = string
  default     = "GitHubActionsWorkflowRole"
}

variable "github_oidc_provider_arn" {
  description = "Optional ARN of an existing account-level GitHub Actions OIDC provider. Leave null to let this Terraform stack create it."
  type        = string
  default     = null

  validation {
    condition = (
      var.github_oidc_provider_arn == null ||
      can(regex("^arn:[^:]+:iam::[0-9]{12}:oidc-provider/token\\.actions\\.githubusercontent\\.com$", var.github_oidc_provider_arn))
    )
    error_message = "github_oidc_provider_arn must be null or the ARN of token.actions.githubusercontent.com in the current AWS account."
  }
}

variable "vpc_cidr" {
  description = "IPv4 CIDR of the application VPC."
  type        = string
  default     = "10.42.0.0/16"
}

variable "public_subnet_cidrs" {
  description = "Exactly two public subnet CIDRs, one per availability zone."
  type        = list(string)
  default     = ["10.42.0.0/24", "10.42.1.0/24"]

  validation {
    condition     = length(var.public_subnet_cidrs) == 2
    error_message = "public_subnet_cidrs must contain exactly two CIDRs."
  }
}

variable "private_subnet_cidrs" {
  description = "Exactly two private subnet CIDRs, one per availability zone."
  type        = list(string)
  default     = ["10.42.10.0/24", "10.42.11.0/24"]

  validation {
    condition     = length(var.private_subnet_cidrs) == 2
    error_message = "private_subnet_cidrs must contain exactly two CIDRs."
  }
}

variable "database_name" {
  description = "Initial PostgreSQL database name."
  type        = string
  default     = "zwanga"
}

variable "database_username" {
  description = "PostgreSQL administrator username. The password is generated by Terraform."
  type        = string
  default     = "zwanga_admin"
}

variable "database_instance_class" {
  description = "RDS instance class."
  type        = string
  default     = "db.t4g.micro"
}

variable "database_allocated_storage_gb" {
  description = "Initial encrypted PostgreSQL storage in GiB."
  type        = number
  default     = 20
}

variable "database_max_allocated_storage_gb" {
  description = "Maximum RDS autoscaled storage in GiB."
  type        = number
  default     = 100
}

variable "database_multi_az" {
  description = "Enable the RDS standby instance in another AZ."
  type        = bool
  default     = false
}

variable "database_deletion_protection" {
  description = "Protect the production database from accidental deletion."
  type        = bool
  default     = true
}

variable "database_skip_final_snapshot" {
  description = "Skip the final RDS snapshot during deletion. Keep false in production."
  type        = bool
  default     = false
}

variable "redis_node_type" {
  description = "ElastiCache Valkey node type."
  type        = string
  default     = "cache.t4g.micro"
}

variable "redis_num_cache_clusters" {
  description = "Number of Redis nodes. Use at least two for automatic failover."
  type        = number
  default     = 1

  validation {
    condition     = var.redis_num_cache_clusters >= 1
    error_message = "redis_num_cache_clusters must be at least 1."
  }
}

variable "ecr_image_retention_count" {
  description = "Number of tagged application images retained in ECR."
  type        = number
  default     = 30
}

variable "ecs_image_tag" {
  description = "Mutable ECR tag deployed by ECS. GitHub Actions refreshes this tag."
  type        = string
  default     = "latest"
}

variable "ecs_container_port" {
  description = "Port exposed by the NestJS container."
  type        = number
  default     = 5200
}

variable "ecs_task_cpu" {
  description = "Fargate task CPU units. 512 = 0.5 vCPU."
  type        = string
  default     = "512"

  validation {
    condition     = contains(["256", "512", "1024", "2048", "4096"], var.ecs_task_cpu)
    error_message = "ecs_task_cpu must be a valid Fargate CPU value."
  }
}

variable "ecs_task_memory" {
  description = "Fargate task memory in MiB. 1024 = 1 GiB."
  type        = string
  default     = "1024"
}

variable "ecs_task_cpu_architecture" {
  description = "Container CPU architecture. ARM64 uses AWS Graviton and matches the GitHub Actions linux/arm64 Docker build."
  type        = string
  default     = "ARM64"

  validation {
    condition     = contains(["X86_64", "ARM64"], var.ecs_task_cpu_architecture)
    error_message = "ecs_task_cpu_architecture must be X86_64 or ARM64."
  }
}

variable "ecs_desired_count" {
  description = "Number of Fargate tasks kept running. Use 1 for the economical always-on profile."
  type        = number
  default     = 1
}

variable "ecs_enable_autoscaling" {
  description = "Enable ECS Service Auto Scaling. Keep false for the most economical launch profile; Redis pub/sub is ready for multi-task Socket.IO when enabled."
  type        = bool
  default     = false
}

variable "ecs_min_capacity" {
  description = "Minimum ECS tasks when autoscaling is enabled."
  type        = number
  default     = 1
}

variable "ecs_max_capacity" {
  description = "Maximum ECS tasks when autoscaling is enabled."
  type        = number
  default     = 6
}

variable "ecs_memory_target_utilization" {
  description = "Target memory utilization percentage for ECS Service Auto Scaling."
  type        = number
  default     = 70
}

variable "ecs_request_count_per_target" {
  description = "Target ALB request count per target for ECS Service Auto Scaling."
  type        = number
  default     = 1000
}

variable "ecs_scale_in_cooldown_seconds" {
  description = "Cooldown before ECS scales in after a scale event."
  type        = number
  default     = 300
}

variable "ecs_scale_out_cooldown_seconds" {
  description = "Cooldown before ECS scales out after a scale event."
  type        = number
  default     = 60
}

variable "ecs_deployment_minimum_healthy_percent" {
  description = "Minimum healthy percent during rolling deployments."
  type        = number
  default     = 100
}

variable "ecs_deployment_maximum_percent" {
  description = "Maximum running percent during rolling deployments."
  type        = number
  default     = 200
}

variable "ecs_wait_for_steady_state" {
  description = "Wait for ECS service stability during terraform apply. Leave false for faster first applies."
  type        = bool
  default     = false
}

variable "enable_ecs_container_insights" {
  description = "Enable ECS Container Insights. This improves metrics but adds CloudWatch cost."
  type        = bool
  default     = false
}

variable "enable_ecs_execute_command" {
  description = "Enable ECS Exec for break-glass debugging through SSM."
  type        = bool
  default     = false
}

variable "alb_certificate_arn" {
  description = "Optional ACM certificate ARN. When set, ALB serves HTTPS and redirects HTTP to HTTPS."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition     = var.alb_certificate_arn == null || can(regex("^arn:", var.alb_certificate_arn))
    error_message = "alb_certificate_arn must be null or a valid ARN."
  }
}

variable "alb_enable_deletion_protection" {
  description = "Protect the ALB from accidental deletion. Disabled for the economical profile."
  type        = bool
  default     = false
}

variable "alb_enable_stickiness" {
  description = "Enable ALB target group stickiness. Recommended for Socket.IO autoscaling when HTTP long-polling can be used before WebSocket upgrade."
  type        = bool
  default     = true
}

variable "alb_stickiness_cookie_duration_seconds" {
  description = "Duration of the ALB stickiness cookie used by Socket.IO clients."
  type        = number
  default     = 86400
}

variable "alb_health_check_path" {
  description = "Application health check path used by the ALB target group."
  type        = string
  default     = "/health"
}

variable "runtime_environment_variables" {
  description = "Additional ECS runtime environment variables. Every entry is stored as an encrypted SSM SecureString and injected into ECS from Parameter Store."
  type        = map(string)
  default     = {}

  validation {
    condition = alltrue([
      for name in keys(var.runtime_environment_variables) :
      can(regex("^[A-Za-z_][A-Za-z0-9_]*$", name))
    ])
    error_message = "runtime_environment_variables keys must be valid environment variable names."
  }

  validation {
    condition = alltrue([
      for value in values(var.runtime_environment_variables) :
      length(value) > 0
    ])
    error_message = "runtime_environment_variables values cannot be empty because SSM parameters require a non-empty value."
  }

  validation {
    condition = length(setintersection(
      toset(keys(var.runtime_environment_variables)),
      toset(["DATABASE_URL", "REDIS_URL", "REDIS_TLS", "JWT_SECRET", "JWT_REFRESH_SECRET", "AOT_CONFIG_CONTENT"]),
    )) == 0
    error_message = "DATABASE_URL, REDIS_URL, JWT_SECRET, JWT_REFRESH_SECRET and AOT_CONFIG_CONTENT are generated separately and must not be set in runtime_environment_variables."
  }
}

variable "external_runtime_environment_variable_names" {
  description = "Environment variable names already created in SSM under /project/environment/env/NAME. Terraform injects them into ECS without storing their values in state."
  type        = set(string)
  default     = []

  validation {
    condition = alltrue([
      for name in var.external_runtime_environment_variable_names :
      can(regex("^[A-Za-z_][A-Za-z0-9_]*$", name))
    ])
    error_message = "external_runtime_environment_variable_names entries must be valid environment variable names."
  }

  validation {
    condition = length(setintersection(
      var.external_runtime_environment_variable_names,
      toset(keys(var.runtime_environment_variables)),
    )) == 0
    error_message = "A variable cannot be declared both in runtime_environment_variables and external_runtime_environment_variable_names."
  }

  validation {
    condition = length(setintersection(
      var.external_runtime_environment_variable_names,
      toset([
        "DATABASE_URL",
        "REDIS_URL",
        "REDIS_TLS",
        "JWT_SECRET",
        "JWT_REFRESH_SECRET",
        "AOT_CONFIG_CONTENT",
        "NODE_ENV",
        "HOST",
        "PORT",
        "API_PREFIX",
        "TYPEORM_SYNCHRONIZE",
        "AWS_REGION",
        "AWS_XRAY_CONTEXT_MISSING",
        "NODE_OPTIONS",
        "OTEL_EXPORTER_OTLP_ENDPOINT",
        "OTEL_EXPORTER_OTLP_PROTOCOL",
        "OTEL_LOGS_EXPORTER",
        "OTEL_METRICS_EXPORTER",
        "OTEL_PROPAGATORS",
        "OTEL_RESOURCE_ATTRIBUTES",
        "OTEL_SERVICE_NAME",
        "OTEL_TRACES_EXPORTER",
        "OTEL_TRACES_SAMPLER",
        "OTEL_TRACES_SAMPLER_ARG",
        "OTEL_AWS_APPLICATION_SIGNALS_ENABLED",
      ]),
    )) == 0
    error_message = "Generated ECS, database, Redis, JWT and OpenTelemetry variables must not be listed as external SSM variables."
  }
}

variable "application_s3_bucket_name" {
  description = "Optional S3 bucket name used by the backend for uploads. When set, the ECS task role receives scoped object permissions and AWS_S3_BUCKET_NAME is injected from SSM."
  type        = string
  default     = null
  nullable    = true
}

variable "enable_rekognition_permissions" {
  description = "Grant the ECS task role permissions required by KYC and content moderation through AWS Rekognition."
  type        = bool
  default     = false
}

variable "extra_tags" {
  description = "Additional tags merged into every AWS resource."
  type        = map(string)
  default     = {}
}

variable "alert_email_addresses" {
  description = "Email addresses subscribed to operational and security alerts. Each subscription must be confirmed."
  type        = set(string)
  default     = []
}

variable "cloudwatch_log_retention_days" {
  description = "Retention for application, database, cache and CloudTrail logs in CloudWatch Logs."
  type        = number
  default     = 7

  validation {
    condition = contains([
      1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731,
      1096, 1827, 2192, 2557, 2922, 3288, 3653,
    ], var.cloudwatch_log_retention_days)
    error_message = "cloudwatch_log_retention_days must be a retention period supported by CloudWatch Logs."
  }
}

variable "cloudtrail_s3_retention_days" {
  description = "Number of days CloudTrail audit objects are retained in the dedicated S3 bucket."
  type        = number
  default     = 365

  validation {
    condition     = var.cloudtrail_s3_retention_days >= 90
    error_message = "CloudTrail logs must be retained for at least 90 days."
  }
}

variable "enable_cloudtrail_insights" {
  description = "Enable CloudTrail Insights for unusual API call and API error rates. Additional charges apply."
  type        = bool
  default     = false
}

variable "enable_xray_tracing" {
  description = "Enable ECS tracing with ADOT sidecar and AWS X-Ray sampling rules."
  type        = bool
  default     = true
}

variable "xray_sampling_rate" {
  description = "X-Ray fixed sampling rate applied after the per-second reservoir is used."
  type        = number
  default     = 0.05

  validation {
    condition     = var.xray_sampling_rate >= 0 && var.xray_sampling_rate <= 1
    error_message = "xray_sampling_rate must be between 0 and 1."
  }
}

variable "rds_enhanced_monitoring_interval_seconds" {
  description = "RDS Enhanced Monitoring interval. Valid values: 0, 1, 5, 10, 15, 30 or 60 seconds."
  type        = number
  default     = 60

  validation {
    condition     = contains([0, 1, 5, 10, 15, 30, 60], var.rds_enhanced_monitoring_interval_seconds)
    error_message = "rds_enhanced_monitoring_interval_seconds must be one of 0, 1, 5, 10, 15, 30 or 60."
  }
}

variable "alarm_evaluation_periods" {
  description = "Number of consecutive periods required before an operational alarm enters ALARM state."
  type        = number
  default     = 2
}

variable "ecs_cpu_alarm_threshold" {
  description = "ECS service CPU utilization alarm threshold in percent."
  type        = number
  default     = 80
}

variable "ecs_memory_alarm_threshold" {
  description = "ECS service memory utilization alarm threshold in percent."
  type        = number
  default     = 80
}

variable "alb_5xx_alarm_threshold" {
  description = "Number of target HTTP 5xx responses in a period before alerting."
  type        = number
  default     = 1
}

variable "alb_latency_alarm_threshold_seconds" {
  description = "ALB target response time alarm threshold in seconds."
  type        = number
  default     = 2
}

variable "rds_cpu_alarm_threshold" {
  description = "RDS CPU utilization alarm threshold in percent."
  type        = number
  default     = 80
}

variable "rds_free_storage_alarm_threshold_bytes" {
  description = "RDS low free storage alarm threshold in bytes. Defaults to 5 GiB."
  type        = number
  default     = 5368709120
}

variable "redis_cpu_alarm_threshold" {
  description = "Redis engine CPU utilization alarm threshold in percent."
  type        = number
  default     = 75
}

variable "redis_memory_alarm_threshold" {
  description = "Redis database memory usage alarm threshold in percent."
  type        = number
  default     = 80
}
