param(
  [string]$EnvFile = (Join-Path $PSScriptRoot "..\..\.env"),
  [string]$ProjectName = "zwanga",
  [string]$Environment = "production",
  [string]$AwsRegion = "eu-west-1",
  [string]$KmsKeyId = "",
  [string]$TerraformNamesFile = (Join-Path $PSScriptRoot "..\external-runtime-variables.auto.tfvars"),
  [bool]$Overwrite = $true
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if (-not (Test-Path -LiteralPath $EnvFile)) {
  throw "Environment file not found: $EnvFile"
}

if (-not (Get-Command aws -ErrorAction SilentlyContinue)) {
  throw "AWS CLI is required and was not found in PATH."
}

if ([string]::IsNullOrWhiteSpace($KmsKeyId)) {
  $KmsKeyId = "alias/$ProjectName-$Environment-application"
}

$excludedNames = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
@(
  "DATABASE_URL",
  "DATABASE_HOST",
  "DATABASE_PORT",
  "DATABASE_USER",
  "DATABASE_PASSWORD",
  "DATABASE_NAME",
  "REDIS_URL",
  "REDIS_HOST",
  "REDIS_PORT",
  "REDIS_PASSWORD",
  "JWT_SECRET",
  "JWT_REFRESH_SECRET",
  "AWS_ACCESS_KEY_ID",
  "AWS_SECRET_ACCESS_KEY",
  "NODE_ENV",
  "HOST",
  "PORT",
  "API_PREFIX",
  "TYPEORM_SYNCHRONIZE",
  "AWS_REGION",
  "ENV_FILE",
  "AOT_CONFIG_CONTENT"
) | ForEach-Object { [void]$excludedNames.Add($_) }

function Convert-DotEnvValue {
  param([string]$RawValue)

  $value = $RawValue.Trim()
  if ($value.Length -ge 2 -and $value.StartsWith('"') -and $value.EndsWith('"')) {
    $value = $value.Substring(1, $value.Length - 2)
    $value = $value.Replace('\"', '"').Replace('\n', "`n").Replace('\r', "`r")
  } elseif ($value.Length -ge 2 -and $value.StartsWith("'") -and $value.EndsWith("'")) {
    $value = $value.Substring(1, $value.Length - 2)
  }

  return $value
}

$importedNames = [System.Collections.Generic.SortedSet[string]]::new([StringComparer]::Ordinal)
$skippedNames = [System.Collections.Generic.List[string]]::new()

Get-Content -LiteralPath $EnvFile | ForEach-Object {
  $line = $_.Trim()

  if ($line.Length -eq 0 -or $line.StartsWith("#")) {
    return
  }

  if ($line -notmatch '^([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$') {
    Write-Warning "Skipping invalid dotenv line: $line"
    return
  }

  $name = $Matches[1]
  $value = Convert-DotEnvValue -RawValue $Matches[2]

  if ($excludedNames.Contains($name) -or $name.StartsWith("DOCKER_") -or $name.StartsWith("POSTGRES_")) {
    [void]$skippedNames.Add($name)
    return
  }

  if ($value.Length -eq 0) {
    Write-Warning "Skipping $name because SSM SecureString values cannot be empty."
    [void]$skippedNames.Add($name)
    return
  }

  $parameterName = "/$ProjectName/$Environment/env/$name"
  $args = @(
    "ssm",
    "put-parameter",
    "--region", $AwsRegion,
    "--name", $parameterName,
    "--type", "SecureString",
    "--key-id", $KmsKeyId,
    "--value", $value
  )

  if ($Overwrite) {
    $args += "--overwrite"
  }

  & aws @args | Out-Null
  if ($LASTEXITCODE -ne 0) {
    throw "aws ssm put-parameter failed for $name"
  }

  [void]$importedNames.Add($name)
  Write-Host "Imported $parameterName"
}

$terraformNamesDirectory = Split-Path -Parent $TerraformNamesFile
if (-not (Test-Path -LiteralPath $terraformNamesDirectory)) {
  New-Item -ItemType Directory -Path $terraformNamesDirectory | Out-Null
}

$tfvarsLines = [System.Collections.Generic.List[string]]::new()
$tfvarsLines.Add("# Generated by scripts/import-env-to-ssm.ps1. Contains names only, not secret values.")
$tfvarsLines.Add("external_runtime_environment_variable_names = [")
foreach ($name in $importedNames) {
  $tfvarsLines.Add("  `"$name`",")
}
$tfvarsLines.Add("]")

Set-Content -LiteralPath $TerraformNamesFile -Value $tfvarsLines -Encoding ascii

Write-Host "Imported $($importedNames.Count) variables into SSM."
Write-Host "Wrote Terraform variable names to $TerraformNamesFile."
if ($skippedNames.Count -gt 0) {
  $uniqueSkipped = $skippedNames | Sort-Object -Unique
  Write-Host "Skipped: $($uniqueSkipped -join ', ')"
}
