import { Body, Controller, Get, Param, Post, Request } from '@nestjs/common';
import { ApiOperation, ApiTags } from '@nestjs/swagger';
import { Auth } from '../auth/decorators/auth.decorator';
import { Public } from '../common/decorators/public.decorator';
import { SensitiveThrottle } from '../common/decorators/sensitive-throttle.decorator';
import { FlexPayCallbackDto } from '../payments/dto/payment.dto';
import {
  ResolveReferralAttributionDto,
  RequestReferralWithdrawalDto,
  ValidateReferralCodeDto,
} from './dto/referral.dto';
import { ReferralsService } from './referrals.service';

interface AuthenticatedRequest {
  user: {
    userId: string;
  };
}

@ApiTags('Referrals')
@Controller('referrals')
export class ReferralsController {
  constructor(private readonly referralsService: ReferralsService) {}

  @Post('validate-code')
  @Public()
  @SensitiveThrottle(20, 60000)
  @ApiOperation({ summary: 'Validate a legacy referral code' })
  validateCode(@Body() dto: ValidateReferralCodeDto) {
    return this.referralsService.validateCode(dto.code);
  }

  @Post('resolve-attribution')
  @Public()
  @SensitiveThrottle(20, 60000)
  @ApiOperation({
    summary: 'Resolve an automatic ChottuLink referral attribution',
  })
  resolveAttribution(@Body() dto: ResolveReferralAttributionDto) {
    return this.referralsService.resolveAttribution(dto.referralToken);
  }

  @Get('me')
  @Auth()
  @SensitiveThrottle(30, 60000)
  @ApiOperation({ summary: 'Get referral link, balances and program rules' })
  getMySummary(@Request() req: AuthenticatedRequest) {
    return this.referralsService.getSummary(req.user.userId);
  }

  @Get('me/referrals')
  @Auth()
  @SensitiveThrottle(30, 60000)
  @ApiOperation({
    summary: 'List direct referrals and the earnings generated by each one',
  })
  getMyReferrals(@Request() req: AuthenticatedRequest) {
    return this.referralsService.getReferrals(req.user.userId);
  }

  @Get('me/rewards')
  @Auth()
  @SensitiveThrottle(30, 60000)
  getMyRewards(@Request() req: AuthenticatedRequest) {
    return this.referralsService.getRewards(req.user.userId);
  }

  @Get('me/ledger')
  @Auth()
  @SensitiveThrottle(30, 60000)
  getMyLedger(@Request() req: AuthenticatedRequest) {
    return this.referralsService.getLedger(req.user.userId);
  }

  @Get('me/withdrawals')
  @Auth()
  @SensitiveThrottle(30, 60000)
  getMyWithdrawals(@Request() req: AuthenticatedRequest) {
    return this.referralsService.getWithdrawals(req.user.userId);
  }

  @Post('me/withdrawals')
  @Auth()
  @SensitiveThrottle(5, 60000)
  requestWithdrawal(
    @Request() req: AuthenticatedRequest,
    @Body() dto: RequestReferralWithdrawalDto,
  ) {
    return this.referralsService.requestWithdrawal(req.user.userId, dto);
  }

  @Post('withdrawals/flexpay/callback')
  @Public()
  @SensitiveThrottle(120, 60000)
  async handleWithdrawalCallback(@Body() dto: FlexPayCallbackDto) {
    const withdrawal =
      await this.referralsService.handleWithdrawalCallback(dto);
    return { received: true, status: withdrawal.status };
  }

  @Get('withdrawals/:orderNumber/status')
  @Auth()
  @SensitiveThrottle(20, 60000)
  checkWithdrawalStatus(
    @Request() req: AuthenticatedRequest,
    @Param('orderNumber') orderNumber: string,
  ) {
    return this.referralsService.checkWithdrawalStatus(
      req.user.userId,
      orderNumber,
    );
  }
}
